In [1]:
import math
import numpy

from discrete_fuzzy_operators.base.operators.binary_operators.discrete.suboperators.fuzzy_discrete_aggregation_operator import DiscreteAggregationBinaryOperator
from discrete_fuzzy_operators.base.operators.binary_operators.discrete.suboperators.fuzzy_discrete_aggregation_suboperators.tconorm import Tconorm
from discrete_fuzzy_operators.base.operators.binary_operators.discrete.fuzzy_discrete_binary_operator import DiscreteBinaryOperator
from discrete_fuzzy_operators.base.operators.binary_operators.discrete.suboperators.fuzzy_discrete_aggregation_suboperators.conjunction import Conjunction

from typing import List, Tuple, Set

Comencem implementant un mètode per a poder visualitzar la regió $X_N$ que ens genera una negació.

In [2]:
def export_matrix_to_latex(matrix: numpy.ndarray, reversed_representation = True):
    operator_matrix = matrix    
    rows_rep = []
    
    rows, cols = operator_matrix.shape
    for i in range(0, rows):
        row_rep = ""
        for j in range(0, cols):
            if j == (cols-1):
                row_rep += rf"{matrix[i,j]} \\"
            else:
                row_rep += rf"{matrix[i,j]} & "
        rows_rep.append(row_rep)
    
    if reversed_representation:
        rows_rep = rows_rep[::-1]
    
    for row_rep in rows_rep:
        print(row_rep)

def get_discontinuities(negation: List[int], n: int) -> List[int]:
    discontinuities = []
    for x in range(0, n):
        if abs(negation[x]-negation[x+1]) > 1:
            discontinuities.append(x)
    return discontinuities

def draw_consistency_set(consistency_set: Set, n: int):
    rows = []
    for y in range(0, n+1):
        row = ""
        for x in range(0, n+1):
            if (x,y) in consistency_set:
                if x == n:
                    row += r"●"
                else:
                    row += r"● "
            else:
                if x == n:
                    row += r"○"
                else:
                    row += r"○ "
        rows.append(row)
    rows.reverse()
    for row in rows:
        print(row)
    print("\n")
    

def draw_consistency_set2(negation: List[int], n: int):
    
    def is_in_region(x: int, y: int, negation: List[int], n):
        negation_discontinuities = get_discontinuities(negation, n)
        for x0 in negation_discontinuities:
            for y0 in negation_discontinuities:
                if ((negation[x0+1]+1) <= x <= (negation[x0]-1)) and ((negation[y0+1]+1) <= y <= (negation[y0]-1)):
                    return True
        return False
    
    rows = []
    for y in range(0, n+1):
        row = ""
        for x in range(0, n+1):
            if is_in_region(x=x, y=y, negation=negation, n=n):
                if x == n:
                    row += r"○"
                else:
                    row += r"○ "
            else:
                if x == n:
                    row += r"●"
                else:
                    row += r"● "
                    
        rows.append(row)
    rows.reverse()
    for row in rows:
        print(row)
    print("\n")

In [3]:
negation = [6,3,3,3,3,0,0]

#draw_consistency_set(consistency_set=A, n=6)
draw_consistency_set2(negation=negation, n=6)

● ● ● ● ● ● ●
● ○ ○ ● ○ ○ ●
● ○ ○ ● ○ ○ ●
● ● ● ● ● ● ●
● ○ ○ ● ○ ○ ●
● ○ ○ ● ○ ○ ●
● ● ● ● ● ● ●




Ara que tenim una representació de $X_N$, estudiem la fita de la cardinalitat del conjunt de punts de no suavitat.

In [4]:
from math import floor

n = 7
discrete_dataset_path = r"C:\Users\Usuario\OneDrive - Universitat de les Illes Balears\UIB\Tesi\Experiments\DiscreteDataset"
negations = numpy.load(discrete_dataset_path+rf"\N={n}\negations.npy", allow_pickle=True)

for negation in negations:
    negation_discontinuities = get_discontinuities(negation, n)
    
    if len(negation_discontinuities) <= (floor(n/2)-1):
        print("Bound ok")
        print("---------------")
    else:
        print("Incorrect bound")
        print(negation)
        print("---------------")

Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Incorrect bound
[7 4 2 0 0 0 0 0]
---------------
Incorrect bound
[7 5 2 0 0 0 0 0]
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Incorrect bound
[7 5 3 0 0 0 0 0]
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------


Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Incorrect bound
[7 5 3 3 3 1 1 0]
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Incorrect bound
[7 5 5 3 3 1 1 0]
---------------
Bound ok
---------------
Incorrect bound
[7 7 5 3 3 1 1 0]
---------------


Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Incorrect bound
[7 5 5 5 5 5 3 0]
---------------
Bound ok
---------------
Incorrect bound
[7 7 5 5 5 5 3 0]
---------------
Bound ok
---------------
Bound ok
---------------
Incorrect bound
[7 7 7 5 5 5 3 0]
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Incorrect bound
[7 7 7 7 5 5 3 0]
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Incorrect bound
[7 7 7 7 7 5 3 0]
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------
Bound ok
---------------


In [5]:
def print_operator(operator: DiscreteBinaryOperator, a: int, b: int):
    occluded_matrix = operator.operator_matrix.astype("str")

    for x in range(0, operator.n+1):
        for y in range(0, operator.n+1):
            if a <=x <= b and a <= y <= b:
                occluded_matrix[y, x] = "-"

    print(numpy.flipud(occluded_matrix))
    

def is_pre_tconorm(operator: DiscreteBinaryOperator, a: int, b: int):
    
    def point_in_region(x: int, y: int, a: int, b: int):
        if a <=x <= b or a <= y <= b:
            return False
        return True
    

    for x in range(0, operator.n+1):
        for y in range(0, operator.n+1):
            for z in range(0, operator.n+1):
                if point_in_region(y,z,a,b) and point_in_region(x,operator.evaluate_operator(y,z),a,b) and point_in_region(x,y,a,b) and point_in_region(operator.evaluate_operator(x,y),z, a, b):
                    if operator.evaluate_operator(x, operator.evaluate_operator(y,z)) != operator.evaluate_operator(operator.evaluate_operator(x,y),z):
                        return False
    return True

#################### CODE FOR FILTERING THOSE SMOOTH AND IDEMPOTENT-FREE DISCRETE PRE-T-CONORMS ####################
def filter_smooth_idempotentfree(a: int, b: int, n: int, tconorms: List[DiscreteBinaryOperator]) -> List[Tconorm]:
    filtered_tconorms = []
    
    for tconorm in tconorms:
        if is_idempotent_free_subregion(a, b, tconorm) and is_smooth_subregion(a, b, tconorm):
            filtered_tconorms.append(tconorm)
    return filtered_tconorms
    
def is_idempotent_free_subregion(a: int, b: int, tconorm: Tconorm) -> bool:
    for x in range(1, tconorm.n):
        if not a <= x <= b:
            if tconorm.evaluate_operator(x, x) == x:
                return False
    return True 

def is_smooth_subregion(a: int, b: int, tconorm: Tconorm) -> bool:
    # STEP 1: Check smoothness of vertical segments
    for x in range(0, tconorm.n+1):
        if a <= x <= b:
            for y in range(0, a-2+1):
                r1 = abs(tconorm.evaluate_operator(x,y+1)-tconorm.evaluate_operator(x,y))
                if r1 > 1:
                    return False
            for y in range(b+1, tconorm.n-1+1):
                r1 = abs(tconorm.evaluate_operator(x,y+1)-tconorm.evaluate_operator(x,y))
                if r1 > 1:
                    return False
        else:
            for y in range(0, tconorm.n-1+1):
                r1 = abs(tconorm.evaluate_operator(x,y+1)-tconorm.evaluate_operator(x,y))
                if r1 > 1:
                    return False
                
    # STEP 2: Check smoothness of horizontal segments
    for y in range(0, tconorm.n+1):
        if a <= y <= b:
            for x in range(0, a-2+1):
                r1 = abs(tconorm.evaluate_operator(x+1,y)-tconorm.evaluate_operator(x,y))
                if r1 > 1:
                    return False
            for x in range(b+1, tconorm.n-1+1):
                r1 = abs(tconorm.evaluate_operator(x+1,y)-tconorm.evaluate_operator(x,y))
                if r1 > 1:
                    return False
        else:
            for x in range(0, tconorm.n-1+1):
                r1 = abs(tconorm.evaluate_operator(x+1,y)-tconorm.evaluate_operator(x,y))
                if r1 > 1:
                    return False
    return True

#################### CODE FOR FILTERING THOSE DISCRETE PRE-T-CONORMS WITH SOME IDEMPOTENT ELEMENT ####################
def get_idempotent_elements(a: int, b: int, tconorm: Tconorm) -> List[int]:
    """
    Computes the non-trivial idempotent elements
    """
    ide = []
    for x in range(1, tconorm.n):
        if not a <= x <= b:
            if tconorm.evaluate_operator(x,x) == x:
                ide.append(x)
    return ide
        

# def is_completable(tconorm: Tconorm, a: int, b: int, verbose: bool = True) -> bool:
#     verboseprint = print if verbose else lambda *a, **k: None
    
#     n = tconorm.n
#     if tconorm.evaluate_operator(n-1, 1) == n:
        
#         condition = True
#         #for x in range(1, n):
#         #    if tconorm.evaluate_operator(x, b+1) != min(n, x+b+1):
#         #        condition = False
#         if tconorm.evaluate_operator(2, b+1) != n:
#             condition = False

#         if condition == True:
#             verboseprint("Fulfilled conditions of Proposition 3.4. The only completion is the discrete t-conorm of Lukasiewicz.")
#             return True
#         else:
#             verboseprint("Fulfilled conditions of Proposition 3.4. It should not come from a smooth t-conorm.")
#             return False
#     else:
#         if a == 1 and b < n-1:
#             # Compute W
#             W = [x for x in range(0, b+1) if tconorm.evaluate_operator(x, b+1) == max(x, b+1)]

#             # Classify
#             if len(W) == 1:
#                 verboseprint("Fulfilled conditions of statement i.a. Trace:")
#                 verboseprint(f"\t |W| = {len(W)}")

#                 return False
#             else:
#                 condition = True
#                 if tconorm.evaluate_operator(n-1, len(W)) != n:
#                     condition = False

#                 for x in range(len(W), n):
#                     if tconorm.evaluate_operator(x, b+1) != min(n, x+b-len(W)+2):
#                         condition = False

#                 if condition == False:
#                     verboseprint("It should not come from a smooth t-conorm. Trace:")
#                     verboseprint(f"\t |W| = {len(W)}")
#                     verboseprint(f"\t Condition: {condition}")

#                     return False
#                 else:
#                     if len(W) == 2  and condition:
#                         verboseprint("Fulfilled conditions of statement i.b. Trace:")
#                         verboseprint(f"\t |W| = {len(W)}")

#                         return True
#                     elif len(W) > 2 and condition:
#                         verboseprint("Fulfilled conditions of statement i.c. Trace:")
#                         verboseprint(f"\t |W| = {len(W)}")

#                         return True
#                     else: 
#                         verboseprint("WARNING: A condition raised in statement (i) which was not expected. Trace:")
#                         verboseprint(f"\t |W| = {len(W)}")
#                         verboseprint(f"\t Condition: {condition}")

#                         return None

#         if a > 1 and b == n-1:
#             # Compute W
#             W = [x for x in range(a, n+1) if tconorm.evaluate_operator(x, a-1) == max(x, a-1)]

#             # Classify
#             if len(W) == 1:
#                 verboseprint("Fulfilled conditions of statement ii.a. Trace:")
#                 verboseprint(f"\t |W| = {len(W)}")

#                 return False
#             else:
#                 condition = True
#                 if tconorm.evaluate_operator(n-len(W), 1) != (n-len(W)+1):
#                     condition = False

#                 for x in range(1, n-len(W)+1):
#                     if tconorm.evaluate_operator(x, a-1) != min(n-len(W)+1, x+a-1):
#                         condition = False

#                 if condition == False:
#                     verboseprint("It should not come from a smooth t-conorm. Trace:")
#                     verboseprint(f"\t |W| = {len(W)}")
#                     verboseprint(f"\t Condition: {condition}")

#                     return False
#                 else:
#                     if len(W) == 2  and condition:
#                         verboseprint("Fulfilled conditions of statement ii.b. Trace:")
#                         verboseprint(f"\t |W| = {len(W)}")

#                         return True
#                     elif len(W) > 2 and condition:
#                         verboseprint("Fulfilled conditions of statement ii.c. Trace:")
#                         verboseprint(f"\t |W| = {len(W)}")

#                         return True
#                     else: 
#                         verboseprint("WARNING: A condition raised in statement (i) which was not expected. Trace:")
#                         verboseprint(f"\t |W| = {len(W)}")
#                         verboseprint(f"\t Condition: {condition}")

#                         return None

#         if a > 1 and b < n-1:
#             # Compute W1 and W2
#             W1 = [x for x in range(0, b+1) if tconorm.evaluate_operator(x, b+1) == max(x, b+1)]
#             W2 = [x for x in range(a, n+1) if tconorm.evaluate_operator(x, a-1) == max(x, a-1)]

#             # Classify
#             if len(W1) == 1 or len(W2) == 1:
#                 verboseprint("It should not come from a smooth t-conorm. Trace:")
#                 verboseprint(f"\t |W1| = {len(W1)}")
#                 verboseprint(f"\t |W2| = {len(W2)}")

#                 return False
#             else:
#                 if (len(W1)-1) == (n-len(W2)+1):

#                     condition = True
#                     if tconorm.evaluate_operator(len(W1)-2, 1) != (len(W1)-1):
#                         condition = False

#                     for x in range(1, len(W1)-1+1):
#                         if tconorm.evaluate_operator(x, a-1) != min(len(W1)-1, x+a-1):
#                             condition = False

#                     if tconorm.evaluate_operator(n-1, len(W1)) != n:
#                         condition = False

#                     for x in range(len(W1), n-1+1):
#                         if tconorm.evaluate_operator(x, b+1) != min(n, x+b-len(W1)+2):
#                             condition = False

#                     if condition == False:
#                         verboseprint("It should not come from a smooth t-conorm. Trace:")
#                         verboseprint(f"\t |W1| = {len(W1)}")
#                         verboseprint(f"\t |W2| = {len(W2)}")
#                         verboseprint(f"\t Condition: {condition}")

#                         return False
#                     else:
#                         verboseprint("Fulfilled conditions of statement iii.a. Trace:")
#                         verboseprint(f"\t |W1| = {len(W1)}")
#                         verboseprint(f"\t |W2| = {len(W2)}")

#                         return True
#                 elif (len(W1)-1) < (n-len(W2)+1):
#                     verboseprint("It should not come from a smooth t-conorm. Trace:")
#                     verboseprint(f"\t |W1| = {len(W1)}")
#                     verboseprint(f"\t |W2| = {len(W2)}")

#                     return False

#                 else:

#                     lambda1 = max(W1)
#                     lambda2 = min(W2)

#                     condition = True
#                     if tconorm.evaluate_operator(n-len(W2), 1) != (n-len(W2)+1):
#                         condition = False

#                     for x in range(1, n-len(W2)+1):
#                         if tconorm.evaluate_operator(x, a-1) != min(n-len(W2)+1, x+a-1):
#                             condition = False

#                     if tconorm.evaluate_operator(n-1, len(W1)) != n:
#                         condition = False

#                     for x in range(len(W1), n-1+1):
#                         if tconorm.evaluate_operator(x, b+1) != min(n, x+b-len(W1)+2):
#                             condition = False

#     #                 for x in range(0, lambda1+1):
#     #                     if tconorm.evaluate_operator(x, b+1) != max(x, b+1):
#     #                         condition = False
#     #                 for x in range(lambda2, n+1):
#     #                     if tconorm.evaluate_operator(x, a-1) != max(x, a-1):
#     #                         condition = False

#                     if condition == False:
#                         verboseprint("It should not come from a smooth t-conorm. Trace:")
#                         verboseprint(f"\t |W1| = {len(W1)}")
#                         verboseprint(f"\t |W2| = {len(W2)}")
#                         verboseprint(f"\t Condition: {condition}")

#                         return False
#                     else:
#                         verboseprint("Fulfilled conditions of statements iii.b and iii.c. Trace:")
#                         verboseprint(f"\t |W1| = {len(W1)}")
#                         verboseprint(f"\t |W2| = {len(W2)}")
#
#                        return True

def is_completable_V2(tconorm: Tconorm, a: int, b: int, verbose: bool = True) -> bool:
    verboseprint = print if verbose else lambda *a, **k: None
    
    n = tconorm.n
    if tconorm.evaluate_operator(n-1, 1) == n:
        
        # The natural negation associated to S is computed
        natural_negation = {}
        for x in range(0,a-1+1):
            temp = [y for y in range(0, n+1) if tconorm.evaluate_operator(x,y) == n]
            natural_negation[x] = min(temp)
        for x in range(b+1,n+1):
            temp = [y for y in range(0, n+1) if tconorm.evaluate_operator(x,y) == n]
            natural_negation[x] = min(temp)
            
        condition = True
        if b <= n-a:
            # Natural negation is smooth on [b+1, n]
            if len(range(b+1,n-1+1)) >= 1:
                for x in range(b+1,n-1+1):
                    if not(abs(natural_negation[x+1]-natural_negation[x]) <= 1):
                        condition = False
                    
        else:
            # Natural negation is strictly decreasing on [0, a-1]
            if len(range(0,a-2+1)) >= 1:
                for x in range(0, a-2+1):
                    if not(natural_negation[x] > natural_negation[x+1]):
                        condition = False

        if condition:
            verboseprint("\t Evaluating the case in which S_A(n-1,1)=n.")
            verboseprint("\t The discrete pre-t-conorm has a unique smooth completion, given by the Lukasiewicz discrete t-conorm.")
            return True
        else:
            verboseprint("\t Evaluating the case in which S_A(n-1,1)=n.")
            verboseprint("\t The discrete pre-t-conorm has no smooth completions.")
            return False
        
    elif tconorm.evaluate_operator(n-1, 1) == (n-1):
        
        if a == 1 and b < (n-1):
            W = [x for x in range(0, b+1) if tconorm.evaluate_operator(x, b+1)==(b+1)]
            
            if len(W) == 1:
                verboseprint("\t Evaluating the case in which S_A(n-1,1)=n-1, a=1 and b<n-1.")
                verboseprint("\t The discrete pre-t-conorm has no smooth completions. ")
            else:
                #The "natural negation" associated to S is computed.
                natural_negation = {}
                for x in range(b+1, n+1):
                    temp = [y for y in range(len(W)-1, n+1) if tconorm.evaluate_operator(x,y) == n]
                    natural_negation[x] = min(temp)
                
                # Natural negation is smooth
                condition = True
                if len(range(b+1,n-1+1)) >= 1:
                    for x in range(b+1,n-1+1):
                        if not(abs(natural_negation[x+1]-natural_negation[x]) <= 1):
                            condition = False
                        
                if condition and len(W) == 2:
                    verboseprint("\t Evaluating the case in which S_A(n-1,1)=n-1, a=1 and b<n-1.")
                    verboseprint("\t The discrete pre-t-conorm has a unique smooth completion, given by an ordinal sum.")
                    return True
                elif condition and len(W) > 2:
                    verboseprint("\t Evaluating the case in which S_A(n-1,1)=n-1, a=1 and b<n-1.")
                    verboseprint(f"\t The discrete pre-t-conorm has {2**(len(W)-2)} smooth completions, given by ordinal sums.")
                    return True
                else:
                    verboseprint("\t Evaluating the case in which S_A(n-1,1)=n-1, a=1 and b<n-1.")
                    verboseprint("\t The discrete pre-t-conorm has no smooth completions.")
                    return False
                
        elif a>1 and b==(n-1):
            
            W = [x for x in range(a, n+1) if tconorm.evaluate_operator(x, a-1)==max(x, a-1)]
            
            if len(W) == 1:
                verboseprint("\t Evaluating the case in which S_A(n-1,1)=n-1, a>1 and b=n-1.")
                verboseprint("\t The discrete pre-t-conorm has no smooth completions. ")
            else:
                #The "natural negation" associated to S is computed.
                natural_negation = {}
                for x in range(0,a-1+1):
                    temp = [y for y in range(0, n+1) if tconorm.evaluate_operator(x,y) == (n-len(W)+1)]
                    natural_negation[x] = min(temp)
                
                # Natural negation is strictly decreasing on [0, a-1]
                condition = True
                if len(range(0,a-2+1)) >= 1:
                    for x in range(0, a-2+1):
                        if not(natural_negation[x] > natural_negation[x+1]):
                            condition = False
            
                if condition and len(W) == 2:
                    verboseprint("\t Evaluating the case in which S_A(n-1,1)=n-1, a>1 and b=n-1.")
                    verboseprint("\t The discrete pre-t-conorm has a unique smooth completion, given by an ordinal sum.")
                    return True
                elif condition and len(W) > 2:
                    verboseprint("\t Evaluating the case in which S_A(n-1,1)=n-1, a>1 and b=n-1.")
                    verboseprint(f"\t The discrete pre-t-conorm has {2**(len(W)-2)} smooth completions, given by ordinal sums.")
                    return True
                else:
                    verboseprint("\t Evaluating the case in which S_A(n-1,1)=n-1, a>1 and b=n-1.")
                    verboseprint("\t The discrete pre-t-conorm has no smooth completions.")
                    return False
                
        else:
            W1 = [x for x in range(0, b+1) if tconorm.evaluate_operator(x,b+1)==(b+1)]
            W2 = [x for x in range(a, n+1) if tconorm.evaluate_operator(x,a-1)==x]
        
            if (len(W1) <= a) or ((n-len(W2))>=b):
                verboseprint("\t Evaluating the case in which S_A(n-1,1)≠n, a>1 and b<n-1.")
                verboseprint("\t The discrete pre-t-conorm has no smooth completions. Case 1.")
                verboseprint("\t Trace:")
                verboseprint(f"\t\t |W1|={len(W1)}")
                verboseprint(f"\t\t |W2|={len(W2)}")
                
                return False
            
            elif ((len(W1)-1)<(n-len(W2)+1)):
                verboseprint("\t Evaluating the case in which S_A(n-1,1)≠n, a>1 and b<n-1.")
                verboseprint("\t The discrete pre-t-conorm has no smooth completions. Case 2.")
                verboseprint("\t Trace:")
                verboseprint(f"\t\t |W1|={len(W1)}")
                verboseprint(f"\t\t |W2|={len(W2)}")
                
                return False
            
            else:
                if (len(W1)-1) == (n-len(W2)+1):
                    # Natural negations are computed
                    natural_negation1 = {}
                    for x in range(0,a-1+1):
                        temp = [y for y in range(0, n+1) if tconorm.evaluate_operator(x,y) == (n-len(W2)+1)]
                        natural_negation1[x] = min(temp)
                        
                    natural_negation2 = {}
                    for x in range(b+1,n+1):
                        temp = [y for y in range(len(W1)-1, n+1) if tconorm.evaluate_operator(x,y) == n]
                        natural_negation2[x] = min(temp)
                                    
                    # Natural negation 1 is strictly decreasing on [0, a-1]
                    condition1 = True
                    if len(range(0,a-2+1)) >= 1:
                        for x in range(0, a-2+1):
                            if not(natural_negation1[x] > natural_negation1[x+1]):
                                condition1 = False
                    
                    # Natural negation 2 is smooth
                    condition2 = True
                    if len(range(b+1,n-1+1)) >= 1:
                        for x in range(b+1,n-1+1):
                            if not(abs(natural_negation2[x+1]-natural_negation2[x]) <= 1):
                                condition2 = False
                    
                    if condition1 and condition2:
                        verboseprint("\t Evaluating the case in which S_A(n-1,1)≠n, a>1 and b<n-1.")
                        verboseprint("\t The discrete pre-t-conorm has a unique smooth completion, given by an ordinal sum. Case 1.")
                        verboseprint("\t Trace:")
                        verboseprint(f"\t\t |W1|={len(W1)}")
                        verboseprint(f"\t\t |W2|={len(W2)}")
                        return True
                    else:
                        verboseprint("\t Evaluating the case in which S_A(n-1,1)≠n, a>1 and b<n-1.")
                        verboseprint("\t The discrete pre-t-conorm has no smooth completions.")
                        verboseprint("\t Trace:")
                        verboseprint(f"\t\t |W1|={len(W1)}")
                        verboseprint(f"\t\t |W2|={len(W2)}")
                        verboseprint(f"\t\t N1 condition: {condition1}")
                        verboseprint(f"\t\t N2 condition: {condition2}")
                        return False
                
                elif (len(W1)-1) == (n-len(W2)+2):
                    # Natural negations are computed
                    natural_negation1 = {}
                    for x in range(0,a-1+1):
                        temp = [y for y in range(0, n+1) if tconorm.evaluate_operator(x,y) == (n-len(W2)+1)]
                        natural_negation1[x] = min(temp)
                        
                    natural_negation2 = {}
                    for x in range(b+1,n+1):
                        temp = [y for y in range(len(W1)-1, n+1) if tconorm.evaluate_operator(x,y) == n]
                        natural_negation2[x] = min(temp)
                                    
                    # Natural negation 1 is strictly decreasing on [0, a-1]
                    condition1 = True
                    if len(range(0,a-2+1)) >= 1:
                        for x in range(0, a-2+1):
                            if not(natural_negation1[x] > natural_negation1[x+1]):
                                condition1 = False
                    
                    # Natural negation 2 is smooth
                    condition2 = True
                    if len(range(b+1,n-1+1)) >= 1:
                        for x in range(b+1,n-1+1):
                            if not(abs(natural_negation2[x+1]-natural_negation2[x]) <= 1):
                                condition2 = False
                    
                    if condition1 and condition2:
                        verboseprint("\t Evaluating the case in which S_A(n-1,1)≠n, a>1 and b<n-1.")
                        verboseprint("\t The discrete pre-t-conorm has a unique smooth completion, given by an ordinal sum. Case 2.")
                        verboseprint("\t Trace:")
                        verboseprint(f"\t\t |W1|={len(W1)}")
                        verboseprint(f"\t\t |W2|={len(W2)}")
                        return True
                    else:
                        verboseprint("\t Evaluating the case in which S_A(n-1,1)≠n, a>1 and b<n-1.")
                        verboseprint("\t The discrete pre-t-conorm has no smooth completions.")
                        verboseprint("\t Trace:")
                        verboseprint(f"\t\t |W1|={len(W1)}")
                        verboseprint(f"\t\t |W2|={len(W2)}")
                        verboseprint(f"\t\t N1 condition: {condition1}")
                        verboseprint(f"\t\t N2 condition: {condition2}")
                        return False
                
                elif (len(W1)-1) > (n-len(W2)+2):
                    # Natural negations are computed
                    natural_negation1 = {}
                    for x in range(0,a-1+1):
                        temp = [y for y in range(0, n+1) if tconorm.evaluate_operator(x,y) == (n-len(W2)+1)]
                        natural_negation1[x] = min(temp)
                        
                    natural_negation2 = {}
                    for x in range(b+1,n+1):
                        temp = [y for y in range(len(W1)-1, n+1) if tconorm.evaluate_operator(x,y) == n]
                        natural_negation2[x] = min(temp)
                                    
                    # Natural negation 1 is strictly decreasing on [0, a-1]
                    condition1 = True
                    if len(range(0,a-2+1)) >= 1:
                        for x in range(0, a-2+1):
                            if not(natural_negation1[x] > natural_negation1[x+1]):
                                condition1 = False
                    
                    # Natural negation 2 is smooth
                    condition2 = True
                    if len(range(b+1,n-1+1)) >= 1:
                        for x in range(b+1,n-1+1):
                            if not(abs(natural_negation2[x+1]-natural_negation2[x]) <= 1):
                                condition2 = False
                    
                    if condition1 and condition2:
                        verboseprint("\t Evaluating the case in which S_A(n-1,1)≠n, a>1 and b<n-1.")
                        verboseprint(f"\t The discrete pre-t-conorm has {2**(len(W1)+len(W2)-n-3)} smooth completions, given by ordinal sums.")
                        verboseprint("\t Trace:")
                        verboseprint(f"\t\t |W1|={len(W1)}")
                        verboseprint(f"\t\t |W2|={len(W2)}")
                        return True
                    else:
                        verboseprint("\t Evaluating the case in which S_A(n-1,1)≠n, a>1 and b<n-1.")
                        verboseprint("\t The discrete pre-t-conorm has no smooth completions.")
                        verboseprint("\t Trace:")
                        verboseprint(f"\t\t |W1|={len(W1)}")
                        verboseprint(f"\t\t |W2|={len(W2)}")
                        verboseprint(f"\t\t N1 condition: {condition1}")
                        verboseprint(f"\t\t N2 condition: {condition2}")
                        return False
                
                else:
                    verboseprint("\t Evaluating the case in which S_A(n-1,1)≠n, a>1 and b<n-1, with an unexpected condition.")
                    verboseprint("\t Trace:")
                    verboseprint(f"\t\t |W1|={len(W1)}")
                    verboseprint(f"\t\t |W2|={len(W2)}")
                    
                    return None
            
    else:
        verboseprint("\t Evaluating the case in which S_A(n-1,1)≠n and S_A(n-1,1)≠n-1, which was not expected.")
        return None
        
            
def find_completions(tconorm: Tconorm, tconorms: List[Tconorm], a: int, b: int):
    completions = []
    
    for completion_candidate in tconorms:
        if is_completion(pre_tconorm=tconorm, candidate_tconorm=completion_candidate, a=a, b=b):
            completions.append(completion_candidate)
    
    return completions
        

def is_completion(pre_tconorm: Tconorm, candidate_tconorm: Tconorm, a: int, b: int):
    for x in range(0, pre_tconorm.n+1):
        for y in range(0, pre_tconorm.n+1):
            if a <=x <= b and a <= y <= b:
                continue
            else:
                if pre_tconorm.evaluate_operator(x,y) != candidate_tconorm.evaluate_operator(x,y):
                    return False
    return True

In [6]:
def generate_luk():
    matrix = numpy.zeros((8+1, 8+1), dtype=int)
    
    for x in range(0, 8+1):
        for y in range(0, 9):
            if (0 <= x <= 3) and (0 <= y <= 3):
                matrix[y,x] = min(3, x+y)
            elif (3 <= x <= 5) and (3 <= y <= 5):
                matrix[y,x] = min(5, x+y-3)
            elif (5 <= x <= 8) and (5 <= y <= 8):
                matrix[y,x] = min(8, x+y-5)
            else:
                matrix[y,x] = max(x,y)
    return matrix

def generate_luk2():
    matrix = numpy.zeros((8+1, 8+1), dtype=int)
    
    for x in range(0, 8+1):
        for y in range(0, 8+1):
            matrix[y,x] = min(8, x+y)
    return matrix

luk_tconorm_od = Tconorm(n=8, operator_matrix=generate_luk())
luk_tconorm = Tconorm(n=8, operator_matrix=generate_luk2())

In [7]:
def already_shown_tconorm(tconorm: Tconorm, a: int, b: int, shown_tconorms: List[str]) -> Tuple[bool, str]:
    tconorm_string_codification = ""
    for x in range(0, tconorm.n+1):
        for y in range(0, tconorm.n+1):
            if not (a <=x <= b and a <= y <= b):
                tconorm_string_codification = tconorm_string_codification+"-"+str(tconorm.evaluate_operator(x,y))
                
    if tconorm_string_codification in shown_tconorms:
        return True, tconorm_string_codification
    return False, tconorm_string_codification

In [8]:
n = 7

discrete_dataset_path = r"C:\Users\Usuario\OneDrive - Universitat de les Illes Balears\UIB\Tesi\Experiments\DiscreteDataset"
commutative_conjunctions_neutral_raw = numpy.load(discrete_dataset_path+rf"\N={n}\conjunctions_commutative_neutralelement_nonassociative.npy", allow_pickle=True)
tconorms_raw = numpy.load(discrete_dataset_path+rf"\N={n}\tconorms.npy", allow_pickle=True)

In [9]:
tconorms = [DiscreteBinaryOperator(n=n, operator_matrix=matrix) for matrix in tconorms_raw]
commutative_disjunctions = [Conjunction(n=n, operator_matrix=matrix).get_dual_disjunction() for matrix in commutative_conjunctions_neutral_raw]

operators = tconorms+commutative_disjunctions

In [11]:
a = 3
b = 6

filtered_results = filter_smooth_idempotentfree(a=a, b=b, n=n, tconorms=operators)
pre_tconorms = [operator for operator in filtered_results if is_pre_tconorm(operator, a, b)]

shown_tconorms = []
idx = 0

for result in pre_tconorms:
        
    if result.evaluate_operator(n-1, 1) == (n):
        shown, codification = already_shown_tconorm(tconorm=result, a=a, b=b, shown_tconorms=shown_tconorms)
        if not shown:
            shown_tconorms.append(codification)

            completions = find_completions(tconorm=result, tconorms=tconorms, a=a, b=b)
            smooth_completions = [completion for completion in completions if completion.is_smooth()]
            nonsmooth_completions = [completion for completion in completions if not completion.is_smooth()]

            print(f"Experiment {idx+1} - Occluded operator:")
            print_operator(operator=result, a=a, b=b)
            already_shown_tconorm(result,a,b,shown_tconorms)
            print("\n")

            print(f"Is pre-t-conorm:  {is_pre_tconorm(result, a, b)}")
            print("\n")

            print("Smooth completions:")
            if len(smooth_completions) == 0:
                print("\t No smooth completions found.")
            else:
                print(f"\t Number of smooth completions found: {len(smooth_completions)}")
                for completion in smooth_completions: 
                    print(numpy.flipud(completion.operator_matrix))
                    
            print("\n")
            print("Non-smooth completions:")
            if len(nonsmooth_completions) == 0:
                print("\t No non-smooth completions found.")
            else:
                print(f"\t Number of non-smooth completions found: {len(nonsmooth_completions)}")
                for completion in nonsmooth_completions: 
                    print(numpy.flipud(completion.operator_matrix))
            

            print("\n")

            print("Statements satisfied:")
            is_completable_V2(tconorm=result, a=a, b=b)
            print("\n")
            print("-----------------")
            print("\n")
            
            idx += 1

Experiment 1 - Occluded operator:
[['7' '7' '7' '7' '7' '7' '7' '7']
 ['6' '7' '7' '-' '-' '-' '-' '7']
 ['5' '6' '7' '-' '-' '-' '-' '7']
 ['4' '5' '6' '-' '-' '-' '-' '7']
 ['3' '4' '5' '-' '-' '-' '-' '7']
 ['2' '3' '4' '5' '6' '7' '7' '7']
 ['1' '2' '3' '4' '5' '6' '7' '7']
 ['0' '1' '2' '3' '4' '5' '6' '7']]


Is pre-t-conorm:  True


Smooth completions:
	 Number of smooth completions found: 1
[[7 7 7 7 7 7 7 7]
 [6 7 7 7 7 7 7 7]
 [5 6 7 7 7 7 7 7]
 [4 5 6 7 7 7 7 7]
 [3 4 5 6 7 7 7 7]
 [2 3 4 5 6 7 7 7]
 [1 2 3 4 5 6 7 7]
 [0 1 2 3 4 5 6 7]]


Non-smooth completions:
	 No non-smooth completions found.


Statements satisfied:
	 Evaluating the case in which S_A(n-1,1)=n.
	 The discrete pre-t-conorm has a unique smooth completion, given by the Lukasiewicz discrete t-conorm.


-----------------


Experiment 2 - Occluded operator:
[['7' '7' '7' '7' '7' '7' '7' '7']
 ['6' '7' '7' '-' '-' '-' '-' '7']
 ['5' '6' '6' '-' '-' '-' '-' '7']
 ['4' '5' '6' '-' '-' '-' '-' '7']
 ['3' '4' '5' '

## Fem una comprovació de tots els casos en què $a=1$ i $b<n-1$, per a tot $n\in \{3, \dots, 7\}$.

In [ ]:
for n in range(3, 7+1):
    commutative_conjunctions_neutral_raw = numpy.load(discrete_dataset_path+rf"\N={n}\conjunctions_commutative_neutralelement_nonassociative.npy", allow_pickle=True)
    tconorms_raw = numpy.load(discrete_dataset_path+rf"\N={n}\tconorms.npy", allow_pickle=True)

    tconorms = [DiscreteBinaryOperator(n=n, operator_matrix=matrix) for matrix in tconorms_raw]
    commutative_disjunctions = [Conjunction(n=n, operator_matrix=matrix).get_dual_disjunction() for matrix in commutative_conjunctions_neutral_raw]

    operators = tconorms+commutative_disjunctions
    
    a = 1
    for b in range(a, n-1):

        filtered_results = filter_smooth_idempotentfree(a=a, b=b, n=n, tconorms=operators)
        pre_tconorms = [operator for operator in filtered_results if is_pre_tconorm(operator, a, b)]

        shown_tconorms = []
        for result in pre_tconorms:
            if result.evaluate_operator(n-1, 1) == (n):
                shown, codification = already_shown_tconorm(tconorm=result, a=a, b=b, shown_tconorms=shown_tconorms)
                if not shown:
                    shown_tconorms.append(codification)

                    completions = find_completions(tconorm=result, tconorms=tconorms, a=a, b=b)
                    smooth_completions = [completion for completion in completions if completion.is_smooth()]

                    if (is_completable_V2(tconorm=result, a=a, b=b, verbose=False) == True and len(smooth_completions) == 0) or (is_completable_V2(tconorm=result, a=a, b=b, verbose=False) == False and len(smooth_completions) > 0):
                        print("Discrepancy found. Trace:")
                        print(f"\t n={n}")
                        print(f"\t a={a}")
                        print(f"\t b={b}")

Comprovem-ho ara en tots els casos en què $b=n-1$ i $a>1$.

In [ ]:
for n in range(3, 7+1):
    commutative_conjunctions_neutral_raw = numpy.load(discrete_dataset_path+rf"\N={n}\conjunctions_commutative_neutralelement_nonassociative.npy", allow_pickle=True)
    tconorms_raw = numpy.load(discrete_dataset_path+rf"\N={n}\tconorms.npy", allow_pickle=True)

    tconorms = [DiscreteBinaryOperator(n=n, operator_matrix=matrix) for matrix in tconorms_raw]
    commutative_disjunctions = [Conjunction(n=n, operator_matrix=matrix).get_dual_disjunction() for matrix in commutative_conjunctions_neutral_raw]

    operators = tconorms+commutative_disjunctions
    
    b = n-1
    for a in range(2, b+1):

        filtered_results = filter_smooth_idempotentfree(a=a, b=b, n=n, tconorms=operators)
        pre_tconorms = [operator for operator in filtered_results if is_pre_tconorm(operator, a, b)]

        shown_tconorms = []
        for result in pre_tconorms:
            if result.evaluate_operator(n-1, 1) == (n):
                shown, codification = already_shown_tconorm(tconorm=result, a=a, b=b, shown_tconorms=shown_tconorms)
                if not shown:
                    shown_tconorms.append(codification)

                    completions = find_completions(tconorm=result, tconorms=tconorms, a=a, b=b)
                    smooth_completions = [completion for completion in completions if completion.is_smooth()]

                    if (is_completable_V2(tconorm=result, a=a, b=b, verbose=False) == True and len(smooth_completions) == 0) or (is_completable_V2(tconorm=result, a=a, b=b, verbose=False) == False and len(smooth_completions) > 0):
                        print("Discrepancy found. Trace:")
                        print(f"\t n={n}")
                        print(f"\t a={a}")
                        print(f"\t b={b}")

Finalment, en tots els casos en què $a>1$ i $b<n-1$.

In [32]:
for n in range(3, 7+1):
    print(f"Working on n={n}")
    commutative_conjunctions_neutral_raw = numpy.load(discrete_dataset_path+rf"\N={n}\conjunctions_commutative_neutralelement_nonassociative.npy", allow_pickle=True)
    tconorms_raw = numpy.load(discrete_dataset_path+rf"\N={n}\tconorms.npy", allow_pickle=True)

    tconorms = [DiscreteBinaryOperator(n=n, operator_matrix=matrix) for matrix in tconorms_raw]
    commutative_disjunctions = [Conjunction(n=n, operator_matrix=matrix).get_dual_disjunction() for matrix in commutative_conjunctions_neutral_raw]

    operators = tconorms+commutative_disjunctions
    
    for a in range(2, n-1):
        for b in range(a, n-1):

            filtered_results = filter_smooth_idempotentfree(a=a, b=b, n=n, tconorms=operators)
            pre_tconorms = [operator for operator in filtered_results if is_pre_tconorm(operator, a, b)]

            shown_tconorms = []
            for result in pre_tconorms:
                if result.evaluate_operator(n-1, 1) == (n):
                    shown, codification = already_shown_tconorm(tconorm=result, a=a, b=b, shown_tconorms=shown_tconorms)
                    if not shown:
                        shown_tconorms.append(codification)

                        completions = find_completions(tconorm=result, tconorms=tconorms, a=a, b=b)
                        smooth_completions = [completion for completion in completions if completion.is_smooth()]

                        if (is_completable_V2(tconorm=result, a=a, b=b, verbose=False) == True and len(smooth_completions) == 0) or (is_completable_V2(tconorm=result, a=a, b=b, verbose=False) == False and len(smooth_completions) > 0):
                            print("Discrepancy found. Trace:")
                            print(f"\t n={n}")
                            print(f"\t a={a}")
                            print(f"\t b={b}")

Working on n=3
Working on n=4
Working on n=5
Working on n=6
Working on n=7


KeyboardInterrupt: 

# Caracterització d'algunes implicacions $(S,N)$ discretes

### Exemple 5.1

In [21]:
import numpy

from discrete_fuzzy_operators.base.operators.unary_operators.suboperators.fuzzy_negation_operator import DiscreteNegation
from discrete_fuzzy_operators.base.operators.binary_operators.discrete.suboperators.fuzzy_discrete_implication_suboperators.sn_implication import SNImplication

# Exemple 1
negation1 = DiscreteNegation(n=8, operator_vector=numpy.array([8,7,7,6,1,1,1,0,0]))
draw_consistency_set2(negation=[8,7,7,6,1,1,1,0,0], n=8)

● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ●
● ● ○ ○ ○ ○ ● ● ●
● ● ○ ○ ○ ○ ● ● ●
● ● ○ ○ ○ ○ ● ● ●
● ● ○ ○ ○ ○ ● ● ●
● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ●




In [22]:
def tconorm1_expression(x: int, y: int, n: int) -> int:
    if 0 <= x <= 2 and 0 <= y <= 2:
        return min(2,x+y)
    elif 2 <= x <= 5 and 2 <= y <= 5:
        return min(5, x+y-2)
    elif 5 <= x <= 8 and 5 <= y <= 8:
        return min(8, x+y-5)
    else:
        return max(x,y)
    
tconorm1 = Tconorm(n=8, operator_expression=tconorm1_expression)
print(numpy.flipud(tconorm1.operator_matrix))

[[8 8 8 8 8 8 8 8 8]
 [7 7 7 7 7 7 8 8 8]
 [6 6 6 6 6 6 7 8 8]
 [5 5 5 5 5 5 6 7 8]
 [4 4 4 5 5 5 6 7 8]
 [3 3 3 4 5 5 6 7 8]
 [2 2 2 3 4 5 6 7 8]
 [1 2 2 3 4 5 6 7 8]
 [0 1 2 3 4 5 6 7 8]]


In [23]:
sn_implication1 = SNImplication(n=8, operator_tconorm=tconorm1, operator_negation=negation1)
print(numpy.flipud(sn_implication1.operator_matrix))

[[8 8 8 8 8 8 8 8 8]
 [8 8 8 8 7 7 7 7 7]
 [8 8 8 7 6 6 6 6 6]
 [8 7 7 6 5 5 5 5 5]
 [8 7 7 6 4 4 4 4 4]
 [8 7 7 6 3 3 3 3 3]
 [8 7 7 6 2 2 2 2 2]
 [8 7 7 6 2 2 2 1 1]
 [8 7 7 6 1 1 1 0 0]]


In [33]:
discrete_dataset_path = r"C:\Users\Usuario\OneDrive - Universitat de les Illes Balears\UIB\Tesi\Experiments\DiscreteDataset"
tconorms_raw = numpy.load(discrete_dataset_path+rf"\N={8}\tconorms.npy", allow_pickle=True)
tconorms = [DiscreteBinaryOperator(n=8, operator_matrix=matrix) for matrix in tconorms_raw]

completions = find_completions(tconorm=tconorm1, tconorms=tconorms, a=2, b=5)
smooth_completions = [completion for completion in completions if completion.is_smooth()]
non_smooth_completions = [completion for completion in completions if not completion.is_smooth()]

print("SMOOTH COMPLETIONS: ")
for s in smooth_completions:
    print(numpy.flipud(s.operator_matrix))
    
print("\n")
print("NON-SMOOTH COMPLETIONS: ")
for s in non_smooth_completions:
    print(numpy.flipud(s.operator_matrix))

SMOOTH COMPLETIONS: 
[[8 8 8 8 8 8 8 8 8]
 [7 7 7 7 7 7 8 8 8]
 [6 6 6 6 6 6 7 8 8]
 [5 5 5 5 5 5 6 7 8]
 [4 4 4 5 5 5 6 7 8]
 [3 3 3 4 5 5 6 7 8]
 [2 2 2 3 4 5 6 7 8]
 [1 2 2 3 4 5 6 7 8]
 [0 1 2 3 4 5 6 7 8]]
[[8 8 8 8 8 8 8 8 8]
 [7 7 7 7 7 7 8 8 8]
 [6 6 6 6 6 6 7 8 8]
 [5 5 5 5 5 5 6 7 8]
 [4 4 4 4 5 5 6 7 8]
 [3 3 3 3 4 5 6 7 8]
 [2 2 2 3 4 5 6 7 8]
 [1 2 2 3 4 5 6 7 8]
 [0 1 2 3 4 5 6 7 8]]
[[8 8 8 8 8 8 8 8 8]
 [7 7 7 7 7 7 8 8 8]
 [6 6 6 6 6 6 7 8 8]
 [5 5 5 5 5 5 6 7 8]
 [4 4 4 4 4 5 6 7 8]
 [3 3 3 4 4 5 6 7 8]
 [2 2 2 3 4 5 6 7 8]
 [1 2 2 3 4 5 6 7 8]
 [0 1 2 3 4 5 6 7 8]]
[[8 8 8 8 8 8 8 8 8]
 [7 7 7 7 7 7 8 8 8]
 [6 6 6 6 6 6 7 8 8]
 [5 5 5 5 5 5 6 7 8]
 [4 4 4 4 4 5 6 7 8]
 [3 3 3 3 4 5 6 7 8]
 [2 2 2 3 4 5 6 7 8]
 [1 2 2 3 4 5 6 7 8]
 [0 1 2 3 4 5 6 7 8]]


NON-SMOOTH COMPLETIONS: 
[[8 8 8 8 8 8 8 8 8]
 [7 7 7 7 7 7 8 8 8]
 [6 6 6 6 6 6 7 8 8]
 [5 5 5 5 5 5 6 7 8]
 [4 4 4 5 5 5 6 7 8]
 [3 3 3 5 5 5 6 7 8]
 [2 2 2 3 4 5 6 7 8]
 [1 2 2 3 4 5 6 7 8]
 [0 1 2 3 4 5 6 7 8]]
[[

### Exemple 5.2

In [64]:
negation2 = DiscreteNegation(n=7, operator_vector=numpy.array([7,7,6,2,2,1,0,0]))
draw_consistency_set2(negation=[7,7,6,2,2,1,0,0], n=7)

● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ●
● ● ● ○ ○ ○ ● ●
● ● ● ○ ○ ○ ● ●
● ● ● ○ ○ ○ ● ●
● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ●




In [65]:
discrete_dataset_path = r"C:\Users\Usuario\OneDrive - Universitat de les Illes Balears\UIB\Tesi\Experiments\DiscreteDataset"
tconorms_raw_n7 = numpy.load(discrete_dataset_path+rf"\N={7}\tconorms.npy", allow_pickle=True)
tconorms_n7 = [DiscreteBinaryOperator(n=7, operator_matrix=matrix) for matrix in tconorms_raw_n7]

non_smooth_tconorms_n7 = [operator for operator in tconorms_n7 if not operator.is_smooth()]
tconorm2 = non_smooth_tconorms_n7[45]
print(numpy.flipud(tconorm2.operator_matrix))

[[7 7 7 7 7 7 7 7]
 [6 7 7 7 7 7 7 7]
 [5 7 7 7 7 7 7 7]
 [4 7 7 7 7 7 7 7]
 [3 3 7 7 7 7 7 7]
 [2 2 7 7 7 7 7 7]
 [1 1 2 3 7 7 7 7]
 [0 1 2 3 4 5 6 7]]


In [66]:
sn_implication2 = SNImplication(n=7, operator_tconorm=tconorm2, operator_negation=negation2)
print(numpy.flipud(sn_implication2.operator_matrix))

[[7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 6 6]
 [7 7 7 7 7 7 5 5]
 [7 7 7 7 7 7 4 4]
 [7 7 7 7 7 3 3 3]
 [7 7 7 7 7 2 2 2]
 [7 7 7 2 2 1 1 1]
 [7 7 6 2 2 1 0 0]]


In [67]:
completions = find_completions(tconorm=tconorm2, tconorms=tconorms_n7, a=3, b=5)
smooth_completions = [completion for completion in completions if completion.is_smooth()]
non_smooth_completions = [completion for completion in completions if not completion.is_smooth()]

print("SMOOTH COMPLETIONS: ")
for s in smooth_completions:
    print(numpy.flipud(s.operator_matrix))
    
print("\n")
print("NON-SMOOTH COMPLETIONS: ")
for s in non_smooth_completions:
    print(numpy.flipud(s.operator_matrix))

SMOOTH COMPLETIONS: 


NON-SMOOTH COMPLETIONS: 
[[7 7 7 7 7 7 7 7]
 [6 7 7 7 7 7 7 7]
 [5 7 7 7 7 7 7 7]
 [4 7 7 7 7 7 7 7]
 [3 3 7 7 7 7 7 7]
 [2 2 7 7 7 7 7 7]
 [1 1 2 3 7 7 7 7]
 [0 1 2 3 4 5 6 7]]


### Exemple 5.3

In [85]:
negation3 = DiscreteNegation(n=6, operator_vector=numpy.array([6,6,6,2,1,1,0]))
draw_consistency_set2(negation=[6,6,6,2,1,1,0], n=6)

● ● ● ● ● ● ●
● ● ● ○ ○ ○ ●
● ● ● ○ ○ ○ ●
● ● ● ○ ○ ○ ●
● ● ● ● ● ● ●
● ● ● ● ● ● ●
● ● ● ● ● ● ●




In [86]:
def tconorm3_expression(x: int, y: int, n: int) -> int:
    if 0 <= x <= 2 and 0 <= y <= 2:
        return min(2,x+y)
    elif 2 <= x <= 5 and 2 <= y <= 5:
        return min(5, x+y-2)
    elif 5 <= x <= 6 and 5 <= y <= 6:
        return min(6, x+y-5)
    else:
        return max(x,y)
    
tconorm3 = Tconorm(n=6, operator_expression=tconorm3_expression)
print(numpy.flipud(tconorm3.operator_matrix))

[[6 6 6 6 6 6 6]
 [5 5 5 5 5 5 6]
 [4 4 4 5 5 5 6]
 [3 3 3 4 5 5 6]
 [2 2 2 3 4 5 6]
 [1 2 2 3 4 5 6]
 [0 1 2 3 4 5 6]]


In [87]:
sn_implication3 = SNImplication(n=6, operator_tconorm=tconorm3, operator_negation=negation3)
print(numpy.flipud(sn_implication3.operator_matrix))

[[6 6 6 6 6 6 6]
 [6 6 6 5 5 5 5]
 [6 6 6 4 4 4 4]
 [6 6 6 3 3 3 3]
 [6 6 6 2 2 2 2]
 [6 6 6 2 2 2 1]
 [6 6 6 2 1 1 0]]


In [88]:
discrete_dataset_path = r"C:\Users\Usuario\OneDrive - Universitat de les Illes Balears\UIB\Tesi\Experiments\DiscreteDataset"
tconorms_raw_n6 = numpy.load(discrete_dataset_path+rf"\N={6}\tconorms.npy", allow_pickle=True)
tconorms_n6 = [DiscreteBinaryOperator(n=6, operator_matrix=matrix) for matrix in tconorms_raw_n6]

completions = find_completions(tconorm=tconorm3, tconorms=tconorms_n6, a=2, b=4)
smooth_completions = [completion for completion in completions if completion.is_smooth()]
non_smooth_completions = [completion for completion in completions if not completion.is_smooth()]

print("SMOOTH COMPLETIONS: ")
for s in smooth_completions:
    print(numpy.flipud(s.operator_matrix))
    
print("\n")
print("NON-SMOOTH COMPLETIONS: ")
for s in non_smooth_completions:
    print(numpy.flipud(s.operator_matrix))

SMOOTH COMPLETIONS: 
[[6 6 6 6 6 6 6]
 [5 5 5 5 5 5 6]
 [4 4 4 5 5 5 6]
 [3 3 3 4 5 5 6]
 [2 2 2 3 4 5 6]
 [1 2 2 3 4 5 6]
 [0 1 2 3 4 5 6]]
[[6 6 6 6 6 6 6]
 [5 5 5 5 5 5 6]
 [4 4 4 4 5 5 6]
 [3 3 3 3 4 5 6]
 [2 2 2 3 4 5 6]
 [1 2 2 3 4 5 6]
 [0 1 2 3 4 5 6]]
[[6 6 6 6 6 6 6]
 [5 5 5 5 5 5 6]
 [4 4 4 4 4 5 6]
 [3 3 3 4 4 5 6]
 [2 2 2 3 4 5 6]
 [1 2 2 3 4 5 6]
 [0 1 2 3 4 5 6]]
[[6 6 6 6 6 6 6]
 [5 5 5 5 5 5 6]
 [4 4 4 4 4 5 6]
 [3 3 3 3 4 5 6]
 [2 2 2 3 4 5 6]
 [1 2 2 3 4 5 6]
 [0 1 2 3 4 5 6]]


NON-SMOOTH COMPLETIONS: 
[[6 6 6 6 6 6 6]
 [5 5 5 5 5 5 6]
 [4 4 4 5 5 5 6]
 [3 3 3 5 5 5 6]
 [2 2 2 3 4 5 6]
 [1 2 2 3 4 5 6]
 [0 1 2 3 4 5 6]]
[[6 6 6 6 6 6 6]
 [5 5 5 5 5 5 6]
 [4 4 4 5 5 5 6]
 [3 3 3 3 5 5 6]
 [2 2 2 3 4 5 6]
 [1 2 2 3 4 5 6]
 [0 1 2 3 4 5 6]]


## Estudi de la completació amb la presència d'elements idempotents

In [14]:
# Exemple associat al Lemma 5.6
discrete_dataset_path = r"C:\Users\Usuario\OneDrive - Universitat de les Illes Balears\UIB\Tesi\Experiments\DiscreteDataset"
tconorms_raw_n8 = numpy.load(discrete_dataset_path+rf"\N={8}\tconorms.npy", allow_pickle=True)
tconorms_n8 = [DiscreteBinaryOperator(n=8, operator_matrix=matrix) for matrix in tconorms_raw_n8]

# Cercam una t-conorma que tengui elements idempotents 1 i 6 (en pot tenir més), que el segment S(1,x) per 1<=x<=6 sigui 
# suau, i que el segment S(6,x) per 6<=x<=8 també sigui suau.

for tconorm in tconorms_n8:
    if tconorm.evaluate_operator(1,1) == 1 and tconorm.evaluate_operator(6,6) == 6: #Elements idempotents
        if tconorm.evaluate_operator(1,2) == 2 and tconorm.evaluate_operator(1,3) == 3 and tconorm.evaluate_operator(1,4) == 4 and tconorm.evaluate_operator(1,5) == 5 and tconorm.evaluate_operator(1,6) == 6: # Segment suau
            if tconorm.evaluate_operator(6,7) == 7:
                print(numpy.flipud(tconorm.operator_matrix))

[[8 8 8 8 8 8 8 8 8]
 [7 7 7 7 7 7 7 8 8]
 [6 6 6 6 6 6 6 7 8]
 [5 5 6 6 6 6 6 7 8]
 [4 4 6 6 6 6 6 7 8]
 [3 3 6 6 6 6 6 7 8]
 [2 2 6 6 6 6 6 7 8]
 [1 1 2 3 4 5 6 7 8]
 [0 1 2 3 4 5 6 7 8]]
[[8 8 8 8 8 8 8 8 8]
 [7 7 7 7 7 7 7 8 8]
 [6 6 6 6 6 6 6 7 8]
 [5 5 6 6 6 6 6 7 8]
 [4 4 6 6 6 6 6 7 8]
 [3 3 6 6 6 6 6 7 8]
 [2 2 5 6 6 6 6 7 8]
 [1 1 2 3 4 5 6 7 8]
 [0 1 2 3 4 5 6 7 8]]
[[8 8 8 8 8 8 8 8 8]
 [7 7 7 7 7 7 7 8 8]
 [6 6 6 6 6 6 6 7 8]
 [5 5 6 6 6 6 6 7 8]
 [4 4 6 6 6 6 6 7 8]
 [3 3 6 6 6 6 6 7 8]
 [2 2 4 6 6 6 6 7 8]
 [1 1 2 3 4 5 6 7 8]
 [0 1 2 3 4 5 6 7 8]]
[[8 8 8 8 8 8 8 8 8]
 [7 7 7 7 7 7 7 8 8]
 [6 6 6 6 6 6 6 7 8]
 [5 5 6 6 6 6 6 7 8]
 [4 4 6 6 6 6 6 7 8]
 [3 3 6 6 6 6 6 7 8]
 [2 2 3 6 6 6 6 7 8]
 [1 1 2 3 4 5 6 7 8]
 [0 1 2 3 4 5 6 7 8]]
[[8 8 8 8 8 8 8 8 8]
 [7 7 7 7 7 7 7 8 8]
 [6 6 6 6 6 6 6 7 8]
 [5 5 6 6 6 6 6 7 8]
 [4 4 6 6 6 6 6 7 8]
 [3 3 6 6 6 6 6 7 8]
 [2 2 2 6 6 6 6 7 8]
 [1 1 2 3 4 5 6 7 8]
 [0 1 2 3 4 5 6 7 8]]
[[8 8 8 8 8 8 8 8 8]
 [7 7 7 7 7 7 7 8 8]
 [6 6 6 

In [12]:
# Contraexemple associat al Lemma 5.6
discrete_dataset_path = r"C:\Users\Usuario\OneDrive - Universitat de les Illes Balears\UIB\Tesi\Experiments\DiscreteDataset"
tconorms_raw_n8 = numpy.load(discrete_dataset_path+rf"\N={8}\tconorms.npy", allow_pickle=True)
tconorms_n8 = [DiscreteBinaryOperator(n=8, operator_matrix=matrix) for matrix in tconorms_raw_n8]

# Cercam una t-conorma que tengui elements idempotents 3 i 6 (en pot tenir més), que el segment S(3,x) per 3<=x<=6 sigui 
# suau, i que el segment S(6,x) per 6<=x<=8 no sigui suau.

for position, tconorm in enumerate(tconorms_n8):
    if tconorm.evaluate_operator(3,3) == 3 and tconorm.evaluate_operator(6,6) == 6 and tconorm.evaluate_operator(2,2) == 2: #Elements idempotents
        if tconorm.evaluate_operator(3,4) == 4 and tconorm.evaluate_operator(3,5) == 5 and tconorm.evaluate_operator(3,6) == 6: # Segment suau
            print(numpy.flipud(tconorm.operator_matrix))
            print(position)
            print("\n")

[[8 8 8 8 8 8 8 8 8]
 [7 8 8 8 8 8 8 8 8]
 [6 6 6 6 6 6 6 8 8]
 [5 5 5 5 6 6 6 8 8]
 [4 4 4 4 6 6 6 8 8]
 [3 3 3 3 4 5 6 8 8]
 [2 2 2 3 4 5 6 8 8]
 [1 2 2 3 4 5 6 8 8]
 [0 1 2 3 4 5 6 7 8]]
10301


[[8 8 8 8 8 8 8 8 8]
 [7 8 8 8 8 8 8 8 8]
 [6 6 6 6 6 6 6 8 8]
 [5 5 5 5 6 6 6 8 8]
 [4 4 4 4 6 6 6 8 8]
 [3 3 3 3 4 5 6 8 8]
 [2 2 2 3 4 5 6 8 8]
 [1 1 2 3 4 5 6 8 8]
 [0 1 2 3 4 5 6 7 8]]
10302


[[8 8 8 8 8 8 8 8 8]
 [7 7 8 8 8 8 8 8 8]
 [6 6 6 6 6 6 6 8 8]
 [5 5 5 5 6 6 6 8 8]
 [4 4 4 4 6 6 6 8 8]
 [3 3 3 3 4 5 6 8 8]
 [2 2 2 3 4 5 6 8 8]
 [1 1 2 3 4 5 6 7 8]
 [0 1 2 3 4 5 6 7 8]]
10303


[[8 8 8 8 8 8 8 8 8]
 [7 7 7 8 8 8 8 8 8]
 [6 6 6 6 6 6 6 8 8]
 [5 5 5 5 6 6 6 8 8]
 [4 4 4 4 6 6 6 8 8]
 [3 3 3 3 4 5 6 8 8]
 [2 2 2 3 4 5 6 7 8]
 [1 2 2 3 4 5 6 7 8]
 [0 1 2 3 4 5 6 7 8]]
10304


[[8 8 8 8 8 8 8 8 8]
 [7 7 7 8 8 8 8 8 8]
 [6 6 6 6 6 6 6 8 8]
 [5 5 5 5 6 6 6 8 8]
 [4 4 4 4 6 6 6 8 8]
 [3 3 3 3 4 5 6 8 8]
 [2 2 2 3 4 5 6 7 8]
 [1 1 2 3 4 5 6 7 8]
 [0 1 2 3 4 5 6 7 8]]
10305


[[8 8 8 8 

In [28]:
# Contraexemple associat a la Proposició 5.15
discrete_dataset_path = r"C:\Users\Usuario\OneDrive - Universitat de les Illes Balears\UIB\Tesi\Experiments\DiscreteDataset"
tconorms_raw_n9 = numpy.load(discrete_dataset_path+rf"\N={9}\tconorms.npy", allow_pickle=True)
tconorms_n9 = [DiscreteBinaryOperator(n=9, operator_matrix=matrix) for matrix in tconorms_raw_n9]

# Cercam una t-conorma que tengui elements idempotents 2 i 9 (en pot tenir més), que el segment S(2,x) per 2<=x<=8 sigui 
# suau, i que el segment S(8,x) per 8<=x<=9 sigui suau.

for tconorm in tconorms_n9:
    idempotents = [2,8]
    have_idempotents = True
    for ide in idempotents:
        if tconorm.evaluate_operator(ide,ide) != ide:
            have_idempotents = False
            break
    
    segment1_smooth = True
    segment1_point = 2
    segment2_smooth = True
    segment2_point = 8
    
    for x in range(segment1_point, segment2_point+1):
        if tconorm.evaluate_operator(segment1_point, x) != x:
            segment1_smooth = False
            break
    
    for x in range(segment2_point, 9):
        if tconorm.evaluate_operator(segment2_point, x) != x:
            segment2_smooth = False
            break
    
    if tconorm.evaluate_operator(segment2_point-1, segment1_point+1) == segment2_point:        
        if have_idempotents and segment1_smooth and segment2_smooth:
            
            suboperator_matrix = tconorm.operator_matrix[segment1_point:(segment2_point+1), segment1_point:(segment2_point+1)]-segment1_point
            suboperator = DiscreteBinaryOperator(n=segment2_point-segment1_point, 
                                                 operator_matrix=suboperator_matrix)
            
            if is_smooth_subregion(a=5-segment1_point, b=6-segment1_point, tconorm=suboperator):
                print(numpy.flipud(tconorm.operator_matrix))
                print(numpy.flipud(suboperator_matrix))

[[9 9 9 9 9 9 9 9 9 9]
 [8 8 8 8 8 8 8 8 8 9]
 [7 7 7 8 8 8 8 8 8 9]
 [6 6 6 7 8 8 8 8 8 9]
 [5 5 5 6 7 8 8 8 8 9]
 [4 4 4 5 6 7 8 8 8 9]
 [3 3 3 4 5 6 7 8 8 9]
 [2 2 2 3 4 5 6 7 8 9]
 [1 2 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
[[6 6 6 6 6 6 6]
 [5 6 6 6 6 6 6]
 [4 5 6 6 6 6 6]
 [3 4 5 6 6 6 6]
 [2 3 4 5 6 6 6]
 [1 2 3 4 5 6 6]
 [0 1 2 3 4 5 6]]
[[9 9 9 9 9 9 9 9 9 9]
 [8 8 8 8 8 8 8 8 8 9]
 [7 7 7 8 8 8 8 8 8 9]
 [6 6 6 7 8 8 8 8 8 9]
 [5 5 5 6 7 8 8 8 8 9]
 [4 4 4 5 6 7 8 8 8 9]
 [3 3 3 4 5 6 7 8 8 9]
 [2 2 2 3 4 5 6 7 8 9]
 [1 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
[[6 6 6 6 6 6 6]
 [5 6 6 6 6 6 6]
 [4 5 6 6 6 6 6]
 [3 4 5 6 6 6 6]
 [2 3 4 5 6 6 6]
 [1 2 3 4 5 6 6]
 [0 1 2 3 4 5 6]]


13775


In [3]:
discrete_dataset_path = r"C:\Users\Usuario\OneDrive - Universitat de les Illes Balears\UIB\Tesi\Experiments\DiscreteDataset"
tconorms_raw_n7 = numpy.load(discrete_dataset_path+rf"\N={7}\tconorms.npy", allow_pickle=True)
tconorms_n7 = [DiscreteBinaryOperator(n=7, operator_matrix=matrix) for matrix in tconorms_raw_n7]

In [29]:
a = 2
b = 3
shown_tconorms = []

for tconorm in tconorms_n7:
    
    shown, codification = already_shown_tconorm(tconorm=tconorm, a=a, b=b, shown_tconorms=shown_tconorms)
    if not shown:
        shown_tconorms.append(codification)
    
        if not is_idempotent_free_subregion(a=a, b=b, tconorm=tconorm):
            idempotent = get_idempotent_elements(a=a, b=b, tconorm=tconorm)
            p1 = idempotent[0]
            
            # CASE B
            if idempotent[0] >= (b+1):
                suboperator_matrix = tconorm.operator_matrix[p1:tconorm.n+1, p1:tconorm.n+1]-p1
                suboperator = DiscreteAggregationBinaryOperator(n=tconorm.n-p1, operator_matrix=suboperator_matrix)
                
                if suboperator.checks_boundary_condition(element=0):
                    print("This operator should have a t-conorm on [a,n]")
                
                if suboperator.is_associative() and suboperator.checks_boundary_condition(element=0):
                    print("This operator has a t-conorm on [a,n].")
                    print_operator(operator=tconorm, a=a, b=b)
                    print(idempotent)
                    print("---------------------")
#                 else:
#                     print("This operator does not have a t-conorm on [a,n].")
#                     print_operator(operator=tconorm, a=a, b=b)
#                     print(idempotent)
#                     print("---------------------")

This operator should have a t-conorm on [a,n]
This operator has a t-conorm on [a,n].
[['7' '7' '7' '7' '7' '7' '7' '7']
 ['6' '6' '6' '6' '6' '7' '7' '7']
 ['5' '5' '5' '5' '5' '7' '7' '7']
 ['4' '4' '4' '4' '4' '5' '6' '7']
 ['3' '4' '-' '-' '4' '5' '6' '7']
 ['2' '4' '-' '-' '4' '5' '6' '7']
 ['1' '4' '4' '4' '4' '5' '6' '7']
 ['0' '1' '2' '3' '4' '5' '6' '7']]
[4]
---------------------
This operator should have a t-conorm on [a,n]
This operator has a t-conorm on [a,n].
[['7' '7' '7' '7' '7' '7' '7' '7']
 ['6' '6' '6' '6' '6' '7' '7' '7']
 ['5' '5' '5' '5' '5' '7' '7' '7']
 ['4' '4' '4' '4' '4' '5' '6' '7']
 ['3' '4' '-' '-' '4' '5' '6' '7']
 ['2' '4' '-' '-' '4' '5' '6' '7']
 ['1' '3' '4' '4' '4' '5' '6' '7']
 ['0' '1' '2' '3' '4' '5' '6' '7']]
[4]
---------------------
This operator should have a t-conorm on [a,n]
This operator has a t-conorm on [a,n].
[['7' '7' '7' '7' '7' '7' '7' '7']
 ['6' '6' '6' '6' '6' '7' '7' '7']
 ['5' '5' '5' '5' '5' '7' '7' '7']
 ['4' '4' '4' '4' '4' '5' 

This operator should have a t-conorm on [a,n]
This operator has a t-conorm on [a,n].
[['7' '7' '7' '7' '7' '7' '7' '7']
 ['6' '6' '6' '6' '6' '6' '6' '7']
 ['5' '5' '5' '5' '5' '5' '6' '7']
 ['4' '5' '5' '5' '5' '5' '6' '7']
 ['3' '5' '-' '-' '5' '5' '6' '7']
 ['2' '4' '-' '-' '5' '5' '6' '7']
 ['1' '4' '4' '5' '5' '5' '6' '7']
 ['0' '1' '2' '3' '4' '5' '6' '7']]
[5, 6]
---------------------
This operator should have a t-conorm on [a,n]
This operator has a t-conorm on [a,n].
[['7' '7' '7' '7' '7' '7' '7' '7']
 ['6' '6' '6' '6' '6' '6' '6' '7']
 ['5' '5' '5' '5' '5' '5' '6' '7']
 ['4' '5' '5' '5' '5' '5' '6' '7']
 ['3' '5' '-' '-' '5' '5' '6' '7']
 ['2' '4' '-' '-' '5' '5' '6' '7']
 ['1' '3' '4' '5' '5' '5' '6' '7']
 ['0' '1' '2' '3' '4' '5' '6' '7']]
[5, 6]
---------------------
This operator should have a t-conorm on [a,n]
This operator has a t-conorm on [a,n].
[['7' '7' '7' '7' '7' '7' '7' '7']
 ['6' '6' '6' '6' '6' '6' '6' '7']
 ['5' '5' '5' '5' '5' '5' '6' '7']
 ['4' '5' '5' '5' '5

In [38]:
n = 2

discrete_dataset_path = r"C:\Users\Usuario\OneDrive - Universitat de les Illes Balears\UIB\Tesi\Experiments\DiscreteDataset"
tconorms_raw = numpy.load(discrete_dataset_path+rf"\N={n}\tconorms.npy", allow_pickle=True)

for matrix in tconorms_raw:
    print(matrix)

[[0 1 2]
 [1 2 2]
 [2 2 2]]
[[0 1 2]
 [1 1 2]
 [2 2 2]]


In [7]:
from discrete_fuzzy_operators.base.operators.binary_operators.discrete.suboperators.fuzzy_discrete_implication_suboperators.sn_implication import SNImplication
from discrete_fuzzy_operators.base.operators.unary_operators.suboperators.fuzzy_negation_operator import DiscreteNegation
from discrete_fuzzy_operators.builtin_operators.discrete.tconorms import TconormExamples
import numpy

negation = DiscreteNegation(n=7, operator_vector=numpy.array([7,7,7,2,2,1,1,0]))
tconorm = TconormExamples.get_tconorm(TconormExamples.LUKASIEWICZ, n=7)
implication = SNImplication(n=7, operator_tconorm=tconorm, operator_negation=negation)
#print(numpy.flipud(implication.operator_matrix))
print(numpy.flipud(tconorm.operator_matrix))

[[7 7 7 7 7 7 7 7]
 [6 7 7 7 7 7 7 7]
 [5 6 7 7 7 7 7 7]
 [4 5 6 7 7 7 7 7]
 [3 4 5 6 7 7 7 7]
 [2 3 4 5 6 7 7 7]
 [1 2 3 4 5 6 7 7]
 [0 1 2 3 4 5 6 7]]


In [52]:
discrete_dataset_path = r"C:\Users\Usuario\OneDrive - Universitat de les Illes Balears\UIB\Tesi\Experiments\DiscreteDataset"
tconorms_raw_n3 = numpy.load(discrete_dataset_path+rf"\N={3}\tconorms.npy", allow_pickle=True)
tconorms_n3 = [DiscreteBinaryOperator(n=3, operator_matrix=matrix) for matrix in tconorms_raw_n3]

# N'agafem una qualsevol de L_3
first_summand = tconorms_n3[3]
print(numpy.flipud(first_summand.operator_matrix))

# N'agafem una qualsevol de L_3
second_summand = tconorms_n3[1]
print(numpy.flipud(second_summand.operator_matrix))

# N'agafem l'altra de L_2
tconorms_raw_n2 = numpy.load(discrete_dataset_path+rf"\N={2}\tconorms.npy", allow_pickle=True)
tconorms_n2 = [DiscreteBinaryOperator(n=3, operator_matrix=matrix) for matrix in tconorms_raw_n2]
third_summand = tconorms_n2[0]
print(third_summand.operator_matrix)

# Montam la suma ordinal
ordinal_sum_matrix = numpy.zeros((9,9), dtype=int)
for x in range(0, 8+1):
    for y in range(0, 8+1):
        ordinal_sum_matrix[y,x] = max(x,y)
ordinal_sum_matrix[0:4, 0:4] = first_summand.operator_matrix
ordinal_sum_matrix[3:7, 3:7] = second_summand.operator_matrix+3
ordinal_sum_matrix[6:9, 6:9] = third_summand.operator_matrix+6
ordinal_sum = Tconorm(n=8, operator_matrix=ordinal_sum_matrix)

print(ordinal_sum_matrix)

negation = DiscreteNegation(n=8, operator_vector=numpy.array([8,8,7,6,3,2,2,1,0]))
draw_consistency_set2(negation=[8,8,7,6,3,2,2,1,0], n=8)

implication = SNImplication(n=8, operator_tconorm=ordinal_sum, operator_negation=negation)
print(numpy.flipud(implication.operator_matrix))
        
export_matrix_to_latex(matrix=implication.operator_matrix)
print("\n")
export_matrix_to_latex(matrix=ordinal_sum.operator_matrix)

[[3 3 3 3]
 [2 2 3 3]
 [1 1 2 3]
 [0 1 2 3]]
[[3 3 3 3]
 [2 3 3 3]
 [1 2 3 3]
 [0 1 2 3]]
[[0 1 2]
 [1 2 2]
 [2 2 2]]
[[0 1 2 3 4 5 6 7 8]
 [1 1 2 3 4 5 6 7 8]
 [2 2 3 3 4 5 6 7 8]
 [3 3 3 3 4 5 6 7 8]
 [4 4 4 4 5 6 6 7 8]
 [5 5 5 5 6 6 6 7 8]
 [6 6 6 6 6 6 6 7 8]
 [7 7 7 7 7 7 7 8 8]
 [8 8 8 8 8 8 8 8 8]]
● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ●
● ● ● ● ○ ○ ● ● ●
● ● ● ● ○ ○ ● ● ●
● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ●


[[8 8 8 8 8 8 8 8 8]
 [8 8 8 7 7 7 7 7 7]
 [8 8 7 6 6 6 6 6 6]
 [8 8 7 6 5 5 5 5 5]
 [8 8 7 6 4 4 4 4 4]
 [8 8 7 6 3 3 3 3 3]
 [8 8 7 6 3 3 3 2 2]
 [8 8 7 6 3 2 2 1 1]
 [8 8 7 6 3 2 2 1 0]]
8 & 8 & 8 & 8 & 8 & 8 & 8 & 8 & 8 \\
8 & 8 & 8 & 7 & 7 & 7 & 7 & 7 & 7 \\
8 & 8 & 7 & 6 & 6 & 6 & 6 & 6 & 6 \\
8 & 8 & 7 & 6 & 5 & 5 & 5 & 5 & 5 \\
8 & 8 & 7 & 6 & 4 & 4 & 4 & 4 & 4 \\
8 & 8 & 7 & 6 & 3 & 3 & 3 & 3 & 3 \\
8 & 8 & 7 & 6 & 3 & 3 & 3 & 2 & 2 \\
8 & 8 & 7 & 6 & 3 & 2 & 2 & 1 & 1 \\
8 & 8 & 7 & 6 & 3 & 2 & 2 & 1 & 0 \\


8 &

In [53]:
print(len(tconorms_n2))

2


In [64]:
tconorm_drastic = TconormExamples.get_tconorm(TconormExamples.NILPOTENT_MAXIMUM, n=2)
tconorm_lukasiewicz = TconormExamples.get_tconorm(TconormExamples.LUKASIEWICZ, n=6)
tconorm_maximum = TconormExamples.get_tconorm(TconormExamples.MAXIMUM, n=1)

# Montam la suma ordinal
ordinal_sum_matrix = numpy.zeros((10,10), dtype=int)
for x in range(0, 9+1):
    for y in range(0, 9+1):
        ordinal_sum_matrix[y,x] = max(x,y)
ordinal_sum_matrix[0:(2+1), 0:(2+1)] = tconorm_drastic.operator_matrix
ordinal_sum_matrix[2:(8+1), 2:(8+1)] = tconorm_lukasiewicz.operator_matrix+2
ordinal_sum_matrix[8:10, 8:10] = tconorm_maximum.operator_matrix+8
ordinal_sum = Tconorm(n=9, operator_matrix=ordinal_sum_matrix)

print(numpy.flipud(ordinal_sum_matrix))

negation = DiscreteNegation(n=9, operator_vector=numpy.array([9,8,8,7,6,6,6,2,1,0]))
draw_consistency_set2(negation=[9,8,8,7,6,6,6,2,1,0], n=9)

implication = SNImplication(n=9, operator_tconorm=ordinal_sum, operator_negation=negation)
print(numpy.flipud(implication.operator_matrix))

export_matrix_to_latex(matrix=implication.operator_matrix)
print("\n")
export_matrix_to_latex(matrix=ordinal_sum.operator_matrix)

[[9 9 9 9 9 9 9 9 9 9]
 [8 8 8 8 8 8 8 8 8 9]
 [7 7 7 8 8 8 8 8 8 9]
 [6 6 6 7 8 8 8 8 8 9]
 [5 5 5 6 7 8 8 8 8 9]
 [4 4 4 5 6 7 8 8 8 9]
 [3 3 3 4 5 6 7 8 8 9]
 [2 2 2 3 4 5 6 7 8 9]
 [1 2 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
● ● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ● ●
● ● ● ○ ○ ○ ● ● ● ●
● ● ● ○ ○ ○ ● ● ● ●
● ● ● ○ ○ ○ ● ● ● ●
● ● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ● ●


[[9 9 9 9 9 9 9 9 9 9]
 [9 8 8 8 8 8 8 8 8 8]
 [9 8 8 8 8 8 8 7 7 7]
 [9 8 8 8 8 8 8 6 6 6]
 [9 8 8 8 8 8 8 5 5 5]
 [9 8 8 8 8 8 8 4 4 4]
 [9 8 8 8 7 7 7 3 3 3]
 [9 8 8 7 6 6 6 2 2 2]
 [9 8 8 7 6 6 6 2 2 1]
 [9 8 8 7 6 6 6 2 1 0]]
9 & 9 & 9 & 9 & 9 & 9 & 9 & 9 & 9 & 9 \\
9 & 8 & 8 & 8 & 8 & 8 & 8 & 8 & 8 & 8 \\
9 & 8 & 8 & 8 & 8 & 8 & 8 & 7 & 7 & 7 \\
9 & 8 & 8 & 8 & 8 & 8 & 8 & 6 & 6 & 6 \\
9 & 8 & 8 & 8 & 8 & 8 & 8 & 5 & 5 & 5 \\
9 & 8 & 8 & 8 & 8 & 8 & 8 & 4 & 4 & 4 \\
9 & 8 & 8 & 8 & 7 & 7 & 7 & 3 & 3 & 3 \\
9 & 8 & 8 & 7 & 6 & 6 & 6 & 2 & 2 & 2 \\
9 & 8 & 

In [71]:
tconorm1 = TconormExamples.get_tconorm(TconormExamples.LUKASIEWICZ, n=1)
tconorm2 = TconormExamples.get_tconorm(TconormExamples.LUKASIEWICZ, n=2)
tconorm3 = TconormExamples.get_tconorm(TconormExamples.LUKASIEWICZ, n=3)
tconorm4 = TconormExamples.get_tconorm(TconormExamples.LUKASIEWICZ, n=2)
tconorm5 = TconormExamples.get_tconorm(TconormExamples.LUKASIEWICZ, n=1)

ordinal_sum_matrix = numpy.zeros((10,10), dtype=int)
for x in range(0, 9+1):
    for y in range(0, 9+1):
        ordinal_sum_matrix[y,x] = max(x,y)
ordinal_sum_matrix[0:(1+1), 0:(1+1)] = tconorm1.operator_matrix
ordinal_sum_matrix[1:(3+1), 1:(3+1)] = tconorm2.operator_matrix+1
ordinal_sum_matrix[3:(6+1), 3:(6+1)] = tconorm3.operator_matrix+3
ordinal_sum_matrix[6:(8+1), 6:(8+1)] = tconorm4.operator_matrix+6
ordinal_sum_matrix[8:(9+1), 8:(9+1)] = tconorm5.operator_matrix+8

ordinal_sum = Tconorm(n=9, operator_matrix=ordinal_sum_matrix)

print(numpy.flipud(ordinal_sum_matrix))

negation = DiscreteNegation(n=9, operator_vector=numpy.array([9,8,7,2,2,2,1,1,1,0]))
draw_consistency_set2(negation=[9,8,7,2,2,2,1,1,1,0], n=9)

implication = SNImplication(n=9, operator_tconorm=ordinal_sum, operator_negation=negation)
print(numpy.flipud(implication.operator_matrix))

export_matrix_to_latex(matrix=implication.operator_matrix)
print("\n")
export_matrix_to_latex(matrix=ordinal_sum.operator_matrix)

[[9 9 9 9 9 9 9 9 9 9]
 [8 8 8 8 8 8 8 8 8 9]
 [7 7 7 7 7 7 7 8 8 9]
 [6 6 6 6 6 6 6 7 8 9]
 [5 5 5 5 6 6 6 7 8 9]
 [4 4 4 4 5 6 6 7 8 9]
 [3 3 3 3 4 5 6 7 8 9]
 [2 2 3 3 4 5 6 7 8 9]
 [1 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
● ● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ● ●
● ● ● ○ ○ ○ ○ ● ● ●
● ● ● ○ ○ ○ ○ ● ● ●
● ● ● ○ ○ ○ ○ ● ● ●
● ● ● ○ ○ ○ ○ ● ● ●
● ● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ● ●


[[9 9 9 9 9 9 9 9 9 9]
 [9 8 8 8 8 8 8 8 8 8]
 [9 8 8 7 7 7 7 7 7 7]
 [9 8 7 6 6 6 6 6 6 6]
 [9 8 7 5 5 5 5 5 5 5]
 [9 8 7 4 4 4 4 4 4 4]
 [9 8 7 3 3 3 3 3 3 3]
 [9 8 7 3 3 3 2 2 2 2]
 [9 8 7 2 2 2 1 1 1 1]
 [9 8 7 2 2 2 1 1 1 0]]
9 & 9 & 9 & 9 & 9 & 9 & 9 & 9 & 9 & 9 \\
9 & 8 & 8 & 8 & 8 & 8 & 8 & 8 & 8 & 8 \\
9 & 8 & 8 & 7 & 7 & 7 & 7 & 7 & 7 & 7 \\
9 & 8 & 7 & 6 & 6 & 6 & 6 & 6 & 6 & 6 \\
9 & 8 & 7 & 5 & 5 & 5 & 5 & 5 & 5 & 5 \\
9 & 8 & 7 & 4 & 4 & 4 & 4 & 4 & 4 & 4 \\
9 & 8 & 7 & 3 & 3 & 3 & 3 & 3 & 3 & 3 \\
9 & 8 & 7 & 3 & 3 & 3 & 2 & 2 & 2 & 2 \\
9 & 8 & 

In [75]:
tconorm_matrix = numpy.array([[0,1,2,3,4,5,6,7,8,9],
                              [1,1,2,3,4,5,6,7,8,9],
                              [2,2,3,3,4,5,6,7,8,9],
                              [3,3,3,3,4,5,6,7,8,9],
                              [4,4,4,4,7,7,7,8,8,9],
                              [5,5,5,5,7,7,7,8,8,9],
                              [6,6,6,6,7,7,8,8,8,9],
                              [7,7,7,7,8,8,8,8,8,9],
                              [8,8,8,8,8,8,8,8,8,9],
                              [9,9,9,9,9,9,9,9,9,9]])

tconorm = Tconorm(n=9, operator_matrix=tconorm_matrix)

negation = DiscreteNegation(n=9, operator_vector=numpy.array([9,9,8,7,6,2,2,1,0,0]))
draw_consistency_set2(negation=[9,9,8,7,6,2,2,1,0,0], n=9)

implication = SNImplication(n=9, operator_tconorm=tconorm, operator_negation=negation)
print(numpy.flipud(implication.operator_matrix))

export_matrix_to_latex(matrix=implication.operator_matrix)
print("\n")
export_matrix_to_latex(matrix=tconorm.operator_matrix)

● ● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ● ●
● ● ● ○ ○ ○ ● ● ● ●
● ● ● ○ ○ ○ ● ● ● ●
● ● ● ○ ○ ○ ● ● ● ●
● ● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ● ●


[[9 9 9 9 9 9 9 9 9 9]
 [9 9 8 8 8 8 8 8 8 8]
 [9 9 8 8 8 7 7 7 7 7]
 [9 9 8 8 8 6 6 6 6 6]
 [9 9 8 8 7 5 5 5 5 5]
 [9 9 8 8 7 4 4 4 4 4]
 [9 9 8 7 6 3 3 3 3 3]
 [9 9 8 7 6 3 3 2 2 2]
 [9 9 8 7 6 2 2 1 1 1]
 [9 9 8 7 6 2 2 1 0 0]]
9 & 9 & 9 & 9 & 9 & 9 & 9 & 9 & 9 & 9 \\
9 & 9 & 8 & 8 & 8 & 8 & 8 & 8 & 8 & 8 \\
9 & 9 & 8 & 8 & 8 & 7 & 7 & 7 & 7 & 7 \\
9 & 9 & 8 & 8 & 8 & 6 & 6 & 6 & 6 & 6 \\
9 & 9 & 8 & 8 & 7 & 5 & 5 & 5 & 5 & 5 \\
9 & 9 & 8 & 8 & 7 & 4 & 4 & 4 & 4 & 4 \\
9 & 9 & 8 & 7 & 6 & 3 & 3 & 3 & 3 & 3 \\
9 & 9 & 8 & 7 & 6 & 3 & 3 & 2 & 2 & 2 \\
9 & 9 & 8 & 7 & 6 & 2 & 2 & 1 & 1 & 1 \\
9 & 9 & 8 & 7 & 6 & 2 & 2 & 1 & 0 & 0 \\


9 & 9 & 9 & 9 & 9 & 9 & 9 & 9 & 9 & 9 \\
8 & 8 & 8 & 8 & 8 & 8 & 8 & 8 & 8 & 9 \\
7 & 7 & 7 & 7 & 8 & 8 & 8 & 8 & 8 & 9 \\
6 & 6 & 6 & 6 & 7 & 7 & 8 & 8 & 

In [100]:
tconorm_matrix = numpy.array([[0,1,2,3,4,5,6,7],
                              [1,2,2,3,4,5,6,7],
                              [2,2,2,3,4,5,6,7],
                              [3,3,3,4,5,6,7,7],
                              [4,4,4,5,6,7,7,7],
                              [5,5,5,6,7,7,7,7],
                              [6,6,6,7,7,7,7,7],
                              [7,7,7,7,7,7,7,7]])
tconorm1 = Tconorm(n=7, operator_matrix=tconorm_matrix)
tconorm2 = TconormExamples.get_tconorm(TconormExamples.DRASTIC, n=3)

ordinal_sum_matrix = numpy.zeros((11,11), dtype=int)
for x in range(0, 10+1):
    for y in range(0, 10+1):
        ordinal_sum_matrix[y,x] = max(x,y)
ordinal_sum_matrix[0:(7+1), 0:(7+1)] = tconorm1.operator_matrix
ordinal_sum_matrix[7:(10+1), 7:(10+1)] = tconorm2.operator_matrix+7
ordinal_sum = Tconorm(n=10, operator_matrix=ordinal_sum_matrix)

negation = DiscreteNegation(n=10, operator_vector=numpy.array([10,10,9,8,7,6,6,1,1,0,0]))
draw_consistency_set2(negation=[10,10,9,8,7,6,6,1,1,0,0], n=10)

implication = SNImplication(n=10, operator_tconorm=ordinal_sum, operator_negation=negation)
print(numpy.flipud(implication.operator_matrix))

export_matrix_to_latex(matrix=implication.operator_matrix)
print("\n")
export_matrix_to_latex(matrix=ordinal_sum.operator_matrix)

● ● ● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ● ● ●
● ● ○ ○ ○ ○ ● ● ● ● ●
● ● ○ ○ ○ ○ ● ● ● ● ●
● ● ○ ○ ○ ○ ● ● ● ● ●
● ● ○ ○ ○ ○ ● ● ● ● ●
● ● ● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ● ● ●


[[10 10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10  9  9  9  9  9  9  9]
 [10 10 10 10  8  8  8  8  8  8  8]
 [10 10  9  8  7  7  7  7  7  7  7]
 [10 10  9  8  7  7  7  6  6  6  6]
 [10 10  9  8  7  7  7  5  5  5  5]
 [10 10  9  8  7  7  7  4  4  4  4]
 [10 10  9  8  7  7  7  3  3  3  3]
 [10 10  9  8  7  6  6  2  2  2  2]
 [10 10  9  8  7  6  6  2  2  1  1]
 [10 10  9  8  7  6  6  1  1  0  0]]
10 & 10 & 10 & 10 & 10 & 10 & 10 & 10 & 10 & 10 & 10 \\
10 & 10 & 10 & 10 & 9 & 9 & 9 & 9 & 9 & 9 & 9 \\
10 & 10 & 10 & 10 & 8 & 8 & 8 & 8 & 8 & 8 & 8 \\
10 & 10 & 9 & 8 & 7 & 7 & 7 & 7 & 7 & 7 & 7 \\
10 & 10 & 9 & 8 & 7 & 7 & 7 & 6 & 6 & 6 & 6 \\
10 & 10 & 9 & 8 & 7 & 7 & 7 & 5 & 5 & 5 & 5 \\
10 & 10 & 9 & 8 & 7 & 7 & 7 & 4 & 4 & 4 & 4 \\
10 & 10 & 9 & 8 &

In [104]:
tconorm_matrix = numpy.array([[0, 1, 2, 3, 4, 5, 6, 7],
                              [1, 2, 3, 3, 4, 5, 6, 7],
                              [2, 3, 3, 3, 4, 5, 6, 7],
                              [3, 3, 3, 3, 4, 5, 6, 7],
                              [4, 4, 4, 4, 6, 6, 7, 7],
                              [5, 5, 5, 5, 6, 6, 7, 7], 
                              [6, 6, 6, 6, 7, 7, 7, 7],
                              [7, 7, 7, 7, 7, 7, 7, 7]])
tconorm2 = Tconorm(n=7, operator_matrix=tconorm_matrix)
tconorm1 = TconormExamples.get_tconorm(TconormExamples.DRASTIC, n=2)

ordinal_sum_matrix = numpy.zeros((10,10), dtype=int)
for x in range(0, 9+1):
    for y in range(0, 9+1):
        ordinal_sum_matrix[y,x] = max(x,y)
ordinal_sum_matrix[0:(2+1), 0:(2+1)] = tconorm1.operator_matrix
ordinal_sum_matrix[2:(9+1), 2:(9+1)] = tconorm2.operator_matrix+2

ordinal_sum = Tconorm(n=9, operator_matrix=ordinal_sum_matrix)

negation = DiscreteNegation(n=9, operator_vector=numpy.array([9,9,9,8,7,3,3,2,1,0]))
draw_consistency_set2(negation=[9,9,9,8,7,3,3,2,1,0], n=9)

implication = SNImplication(n=9, operator_tconorm=ordinal_sum, operator_negation=negation)
print(numpy.flipud(implication.operator_matrix))

export_matrix_to_latex(matrix=implication.operator_matrix)
print("\n")
export_matrix_to_latex(matrix=ordinal_sum.operator_matrix)

● ● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ● ●
● ● ● ● ○ ○ ○ ● ● ●
● ● ● ● ○ ○ ○ ● ● ●
● ● ● ● ○ ○ ○ ● ● ●
● ● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ● ●


[[9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 8 8 8 8 8]
 [9 9 9 9 8 7 7 7 7 7]
 [9 9 9 9 8 6 6 6 6 6]
 [9 9 9 8 7 5 5 5 5 5]
 [9 9 9 8 7 5 5 4 4 4]
 [9 9 9 8 7 4 4 3 3 3]
 [9 9 9 8 7 3 3 2 2 2]
 [9 9 9 8 7 3 3 2 2 1]
 [9 9 9 8 7 3 3 2 1 0]]
9 & 9 & 9 & 9 & 9 & 9 & 9 & 9 & 9 & 9 \\
9 & 9 & 9 & 9 & 9 & 8 & 8 & 8 & 8 & 8 \\
9 & 9 & 9 & 9 & 8 & 7 & 7 & 7 & 7 & 7 \\
9 & 9 & 9 & 9 & 8 & 6 & 6 & 6 & 6 & 6 \\
9 & 9 & 9 & 8 & 7 & 5 & 5 & 5 & 5 & 5 \\
9 & 9 & 9 & 8 & 7 & 5 & 5 & 4 & 4 & 4 \\
9 & 9 & 9 & 8 & 7 & 4 & 4 & 3 & 3 & 3 \\
9 & 9 & 9 & 8 & 7 & 3 & 3 & 2 & 2 & 2 \\
9 & 9 & 9 & 8 & 7 & 3 & 3 & 2 & 2 & 1 \\
9 & 9 & 9 & 8 & 7 & 3 & 3 & 2 & 1 & 0 \\


9 & 9 & 9 & 9 & 9 & 9 & 9 & 9 & 9 & 9 \\
8 & 8 & 8 & 8 & 8 & 8 & 9 & 9 & 9 & 9 \\
7 & 7 & 7 & 7 & 7 & 7 & 8 & 8 & 9 & 9 \\
6 & 6 & 6 & 6 & 6 & 6 & 8 & 8 & 

In [22]:
tconorm_matrix = numpy.array([[0, 1, 2, 3, 4, 5, 6, 7, 8],
                              [1, 2, 2, 3, 4, 5, 6, 8, 8],
                              [2, 2, 2, 3, 4, 5, 6, 8, 8],
                              [3, 3, 3, 3, 4, 5, 6, 8, 8],
                              [4, 4, 4, 4, 6, 6, 6, 8, 8],
                              [5, 5, 5, 5, 6, 6, 6, 8, 8], 
                              [6, 6, 6, 6, 6, 6, 6, 8, 8],
                              [7, 8, 8, 8, 8, 8, 8, 8, 8],
                              [8, 8, 8, 8, 8, 8, 8, 8, 8]])
tconorm = Tconorm(n=8, operator_matrix=tconorm_matrix)
negation = DiscreteNegation(n=8, operator_vector=numpy.array([8,7,6,6,3,2,2,1,0]))
draw_consistency_set2(negation=[8,7,6,6,3,2,2,1,0], n=8)

implication = SNImplication(n=8, operator_tconorm=tconorm, operator_negation=negation)
print(numpy.flipud(implication.operator_matrix))

export_matrix_to_latex(matrix=implication.operator_matrix)

● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ●
● ● ● ● ○ ○ ● ● ●
● ● ● ● ○ ○ ● ● ●
● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ●
● ● ● ● ● ● ● ● ●


[[8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 7]
 [8 8 6 6 6 6 6 6 6]
 [8 8 6 6 5 5 5 5 5]
 [8 8 6 6 4 4 4 4 4]
 [8 8 6 6 3 3 3 3 3]
 [8 8 6 6 3 2 2 2 2]
 [8 8 6 6 3 2 2 2 1]
 [8 7 6 6 3 2 2 1 0]]
8 & 8 & 8 & 8 & 8 & 8 & 8 & 8 & 8 \\
8 & 8 & 8 & 8 & 8 & 8 & 8 & 8 & 7 \\
8 & 8 & 6 & 6 & 6 & 6 & 6 & 6 & 6 \\
8 & 8 & 6 & 6 & 5 & 5 & 5 & 5 & 5 \\
8 & 8 & 6 & 6 & 4 & 4 & 4 & 4 & 4 \\
8 & 8 & 6 & 6 & 3 & 3 & 3 & 3 & 3 \\
8 & 8 & 6 & 6 & 3 & 2 & 2 & 2 & 2 \\
8 & 8 & 6 & 6 & 3 & 2 & 2 & 2 & 1 \\
8 & 7 & 6 & 6 & 3 & 2 & 2 & 1 & 0 \\
